-- Migration: initial_schema
-- Project: Oudora
-- Generated by: Database Engineer Agent

BEGIN;

-- ── TABLES ──────────────────────────────────────────────────────────────────

-- Table: leads
CREATE TABLE IF NOT EXISTS leads (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── UPDATED_AT TRIGGER ───────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_updated_at
  BEFORE UPDATE ON leads
  FOR EACH ROW EXECUTE PROCEDURE handle_updated_at();

-- ── ROW LEVEL SECURITY ───────────────────────────────────────────────────────

ALTER TABLE leads ENABLE ROW LEVEL SECURITY;

-- Enable insert: Public (Allow users to submit the form)
CREATE POLICY "Allow public insert" ON leads
  FOR INSERT WITH CHECK (true);

-- Enable select: Authenticated (Admin only)
CREATE POLICY "Allow authenticated select" ON leads
  FOR SELECT TO authenticated USING (true);

COMMIT;